# Generated by Django 4.1.2 on 2022-11-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('age', models.IntegerField(verbose_name='Год')),
                ('body', models.CharField(max_length=50, verbose_name='Кузов')),
                ('shift', models.CharField(max_length=50, verbose_name='КПП')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('engine', models.CharField(max_length=50, verbose_name='Двигатель')),
                ('volume', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Объем двигателя')),
                ('driveunit', models.CharField(max_length=50, verbose_name='Привод')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('comment', models.CharField(max_length=1000, verbose_name='Комментарий')),
                ('photo', models.ImageField(upload_to='main/img/', verbose_name='Фото')),
            ],
        ),
    ]
