# Generated by Django 4.1.2 on 2022-11-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ad_body_alter_ad_driveunit_alter_ad_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='body',
            field=models.CharField(choices=[['Седан', 'Седан'], ['Хэтчбек 3 дв.', 'Хэтчбек 3 дв.'], ['Хэтчбек 5 дв.', 'Хэтчбек 5 дв.'], ['Лифтбек', 'Лифтбек'], ['Внедорожник', 'Внедорожник'], ['Универсал', 'Универсал'], ['Купе', 'Купе'], ['Минивэн', 'Минивэн'], ['Лимузин', 'Лимузин'], ['Кабриолет', 'Кабриолет']], max_length=50, verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='driveunit',
            field=models.CharField(choices=[['Передний', 'Передний'], ['Задний', 'Задний'], ['Полный', 'Полный']], max_length=50, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='engine',
            field=models.CharField(choices=[['Бензин', 'Бензин'], ['Дизель', 'Дизель'], ['Гибрид', 'Гибрид'], ['Электро', 'Электро']], max_length=50, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='shift',
            field=models.CharField(choices=[['Автоматическая', 'Автоматическая'], ['Робот', 'Робот'], ['Механическая', 'Механическая']], max_length=50, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='volume',
            field=models.CharField(choices=[['0.2 л', '0.2 л'], ['0.3 л', '0.3 л'], ['0.4 л', '0.4 л'], ['0.5 л', '0.5 л'], ['0.6 л', '0.6 л'], ['0.7 л', '0.7 л'], ['0.8 л', '0.8 л'], ['0.9 л', '0.9 л'], ['1.0 л', '1.0 л'], ['1.1 л', '1.1 л'], ['1.2 л', '1.2 л'], ['1.3 л', '1.3 л'], ['1.4 л', '1.4 л'], ['1.5 л', '1.5 л'], ['1.6 л', '1.6 л'], ['1.7 л', '1.7 л'], ['1.8 л', '1.8 л'], ['1.9 л', '1.9 л'], ['2.0 л', '2.0 л'], ['2.1 л', '2.1 л'], ['2.2 л', '2.2 л'], ['2.3 л', '2.3 л'], ['2.4 л', '2.4 л'], ['2.5 л', '2.5 л'], ['2.6 л', '2.6 л'], ['2.7 л', '2.7 л'], ['2.8 л', '2.8 л'], ['2.9 л', '2.9 л'], ['3.0 л', '3.0 л'], ['3.5 л', '3.5 л'], ['4.0 л', '4.0 л'], ['4.5 л', '4.5 л'], ['5.0 л', '5.0 л'], ['5.5 л', '5.5 л'], ['6.0 л', '6.0 л'], ['7.0 л', '7.0 л'], ['8.0 л', '8.0 л'], ['9.0 л', '9.0 л'], ['10.0 л', '10.0 л']], max_length=50, verbose_name='Объем двигателя'),
        ),
    ]
