# Generated by Django 4.1.2 on 2022-11-28 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_ad_body_alter_ad_driveunit_alter_ad_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='Комментарий'),
        ),
    ]
