# Generated by Django 4.1.2 on 2022-11-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
    ]
