# Generated by Django 4.1.2 on 2022-11-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='main/img', upload_to='main/img/imgavto'),
        ),
    ]
