# Generated by Django 4.1.2 on 2023-03-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='main/img/a.jpg', upload_to='main/img/imgavto', verbose_name='Фото'),
        ),
    ]
